version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: keytar
    versions:
    - 7.3.0
    - 7.4.0
    - 7.5.0
    - 7.6.0
  - dependency-name: relay-runtime
    versions:
    - 10.1.3
    - 11.0.0
    - 11.0.1
  - dependency-name: react-relay
    versions:
    - 10.1.3
    - 11.0.0
    - 11.0.1
  - dependency-name: react-select
    versions:
    - 4.0.2
    - 4.1.0
    - 4.2.0
    - 4.2.1
